name: helloworld
 
on:
  push:
 
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Builing the package
        run: |
        echo "building the c package"
        mkdir -p build
        cd build
        cmake ..
        make
 
